### ISSUE TITLE
Background is white

### ISSUE THREAD

**Issue by AtlasRider** [QzSG/kitty-time#2]
How can I change the background to a dark color?

**Comment by QzSG** [comment]
Currently it should be dark if u are using a "dark theme" and light if u are using a "light theme", there are some other visual bugs that I haven got around to fixing due to my busy schedule recently, if u have a fix or want to contribute to add a custom bg color  and corresponding font css feel free to send in a pr! If not I might only be fixing and adding features in a month or two (aside from crticial issues or security issues).

My apologies! :cat:

**Comment by QzSG** [comment]
I am currently trying to do a quick fix, looks like the behavior i mentioned above broke, will fix and update packages too

**Comment by QzSG** [comment]
@AtlasRider I have just pushed `0.3.0` to the Extension marketplace, please update and let me know if it works correctly now, or if anything else broke (which should not happen). I will add the option to use a custom bg color the next time around

**Comment by QzSG** [comment]
@AtlasRider please close the issue if it's working as u expected it to be, thanks!
